name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests and send coverage to Coveralls
      run: |
        npm run test-coverage  # Runs the test coverage using npm
      env: 
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Check if lcov.info exists
      run: |
        ls -l ./coverage  # This will list the contents of the coverage folder to debug

    - name: Coveralls
      uses: coverallsapp/github-action@v2
