name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests and collect coverage
      run: |
        npm run test-coverage  # Runs the test coverage using npm and c8
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Verify coverage files
      run: |
        echo "Listing contents of ./coverage directory:"
        ls -lh ./coverage  # This ensures the lcov.info file is generated

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: ./coverage/lcov.info  # Specify the location of the coverage report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
